import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  generator: 'Next.js',
  keywords: ['nextjs', 'nextjs14', 'pwa', 'next-pwa'],
  themeColor: [{ media: '(prefers-color-scheme:dark)', color: '#fff' }],
  authors: [
    {
      name: 'mehran',
      url: 'https://www.linkedin.com/in/mehranbhat/',
    },
  ],
  viewport:
    'minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover',
  icons: [
    { rel: 'apple-touch-icon', url: '/b2ctrading-512.png' },
    { rel: 'icon', url: '/b2ctrading-512.png' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='theme-color' content='#fffff' />
        <link rel='mainfest' href='/mainfest.json' />
        <link rel='icon' href='/b2ctrading-512.png' />
        <link rel='apple-touch-icon' href='/b2ctrading-512.png' />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
